export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",
  // Points / kudos
  INSUFFICIENT_BUDGET: "INSUFFICIENT_BUDGET",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  SELF_KUDO_FORBIDDEN: "SELF_KUDO_FORBIDDEN",
  MEDIA_NOT_READY: "MEDIA_NOT_READY",
  // Admin
  SELF_ROLE_EDIT_FORBIDDEN: "SELF_ROLE_EDIT_FORBIDDEN",
  SELF_DELETE_FORBIDDEN: "SELF_DELETE_FORBIDDEN",
  // Rewards
  REWARD_INACTIVE: "REWARD_INACTIVE",
  REWARD_OUT_OF_STOCK: "REWARD_OUT_OF_STOCK",
  // Generic
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL: "INTERNAL",
} as const

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode]
